ARCHS=armv7

include /opt/theos/makefiles/common.mk

APPLICATION_NAME = RemoteViewClient
RemoteViewClient_FILES = main.m RemoteViewClientApplication.mm RootViewController.mm
RemoteViewClient_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
