ARCHS=armv7

include /opt/theos/makefiles/common.mk

APPLICATION_NAME = RemoteViewServer
RemoteViewServer_FILES = main.m RemoteViewServerApplication.mm RootViewController.mm
RemoteViewServer_FRAMEWORKS = UIKit CoreGraphics MessageUI

include $(THEOS_MAKE_PATH)/application.mk
