ARCHS=armv7

include /opt/theos/makefiles/common.mk

TWEAK_NAME = LibRemoteViewServer
LibRemoteViewServer_FILES = Tweak.xm
LibRemoteViewServer_FRAMEWORKS = UIKit Foundation
LibRemoteViewServer_LDFLAGS = -ldisplay

include $(THEOS_MAKE_PATH)/tweak.mk
